src/ChinookSolution/WebApp/Pages/SamplePages/Basics.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages.SamplePages
{
    public class BasicsModel : PageModel
    {
        //  Basically this is an object, treat it as such

        //  data fields

        //  properties
        //  The annotation {TempData] stores data until it's read in another
        //      immediate request
        //  This annotation attribute has two method called Keep(string) and
        //      peek(string) (used on Content page).
        //  Keep in a dictionary (name/value pair)
        //  Useful to redirect when data is required for more than a single request
        //  Implemented by TempData providers using either cookies or session state
        //  TempData is NOT bound to any particular control like BindProperty
        [TempData]
        public string FeedBack { get; set; }

        //  The annotation BindProperty ties a property in the PageModel Class
        //      directly to a control on the Content Page
        //  Data is transferred between the two automatically
        //  On the Content page, the control to use this property will have
        //      a helper-tag called asp-for
        [BindProperty]
        public int ID { get; set; }
        public string MyName { get; set; }



        //  constructors

        //  behaviours (aka methods)

        public void OnGet()
        {
            //  Execute in response to a Get Request from the browser
            //  When the page is "first" accessed, the browser issue a Get request
            //  When the page is refreshed, WITHOUT a post request, the browser issues a
            //      Get Request
            //  When the page is retrieved in response to a forms's post, using
            //      RedirectToPage()
            //  IF NOT RedirectToPage() is used on the POST, there is NO Get requested issue

            Random rnd = new Random();
            int oddEven = rnd.Next(0, 25);
            if (oddEven % 2 == 0)
            {
                MyName = $"James is even {oddEven}";
            }
            else
            {
                MyName = null;
            }
        }
    }
}

src/ChinookSolution/WebApp/Pages/SamplePages/Controls.cshtml.cs
#nullable disable
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;


namespace WebApp.Pages.SamplePages
{
    public class ControlsModel : PageModel
    {
        [TempData]
        public string Feedback { get; set; }

        [BindProperty]
        public string EmailText { get; set; }
        [BindProperty]
        public string PasswordText { get; set; }

        [BindProperty] public DateTime DateText { get; set; } = DateTime.Today;
        [BindProperty] public TimeSpan TimeText { get; set; } = DateTime.Now.TimeOfDay;

        [BindProperty]
        public string Meal { get; set; }

        //  assume this array is actually data retrieved from the database
        public string[] Meals { get; set; } = new string[] { "breakfast", "lunch", "dinner", "snacks" };

        [BindProperty]
        public bool AcceptanceBox { get; set; }

        [BindProperty]
        public string MessageBody { get; set; }

        [BindProperty]
        public int MyRide { get; set; }

        //  pretend tat the following collection is data from a database
        //  The collection is based on a 2 property class called SelectionList
        //  The data for the list will be created in a separate method.
        public List<SelectionList> Rides { get; set; }

        [BindProperty]
        public string VacationSpot { get; set; }

        public List<string> VacationSpots { get; set; }

        [BindProperty]
        public int ReviewRating { get; set; }
        public IActionResult OnPostTextBox()
        {
            Feedback = $"Email {EmailText}; Password {PasswordText}; Date {DateText.ToShortDateString()}; Time {TimeText}";
            return Page();
        }
        public IActionResult OnPostRadioCheckArea()
        {
            Feedback = $"Meal {Meal}; Acceptance {AcceptanceBox}; Message {MessageBody}";
            return Page();
        }

        public IActionResult OnPostListSlider()
        {
            Feedback = $"Ride {MyRide}; Vacation {VacationSpot}; Review Rating {ReviewRating}";
            PopulatedList();
            return Page();
        }





        public void OnGet()
        {
            PopulatedList();
        }

        private void PopulatedList()
        {
            int i = 1;
            //  Create a pretend collection from the database represents different types
            //      of transportation (rides)
            Rides = new List<SelectionList>();
            Rides.Add(new SelectionList() { ValueID = i++, DisplayText = "Car" });
            Rides.Add(new SelectionList() { ValueID = i++, DisplayText = "Bus" });
            Rides.Add(new SelectionList() { ValueID = i++, DisplayText = "Bike" });
            Rides.Add(new SelectionList() { ValueID = i++, DisplayText = "Motorcycle" });
            Rides.Add(new SelectionList() { ValueID = i++, DisplayText = "Boat" });
            Rides.Add(new SelectionList() { ValueID = i++, DisplayText = "Plane" });
            Rides.Sort((x,y) => x.DisplayText.CompareTo(y.DisplayText));

            VacationSpots = new List<string>();
            VacationSpots.Add("California");
            VacationSpots.Add("Caribbean");
            VacationSpots.Add("Cruising");
            VacationSpots.Add("Europe");
            VacationSpots.Add("Florida");
            VacationSpots.Add("Mexico");

        }
    }

}

src/ChinookSolution/WebApp/Pages/SamplePages/PlaylistManagement.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

#region Additional 
using ChinookSystem.ViewModels;
using WebApp.Helpers;
using ChinookSystem.BLL;
#endregion


namespace WebApp.Pages.SamplePages
{

    public class PlaylistManagementModel : PageModel
    {
        #region Private variables and DI constructor
        private readonly TrackServices _trackServices;
        private readonly PlaylistTrackServices _playlisttrackServices;


        public PlaylistManagementModel(TrackServices trackservices,
                                PlaylistTrackServices playlisttrackservices)
        {
            _trackServices = trackservices;
            _playlisttrackServices = playlisttrackservices;
        }
        #endregion

        #region Messaging and Error Handling
        [TempData]
        public string FeedBackMessage { get; set; }
        
        public string ErrorMessage { get; set; }

        //a get property that returns the result of the lamda action
        public bool HasError => !string.IsNullOrWhiteSpace(ErrorMessage);
        public bool HasFeedBack => !string.IsNullOrWhiteSpace(FeedBackMessage);

        //used to display any collection of errors on web page
        //whether the errors are generated locally OR come form the class library
        //      service methods
        public List<string> ErrorDetails { get; set; } = new();

        //PageModel local error list for collection 
        public List<Exception> Errors { get; set; } = new();

        #endregion

        #region Paginator
        private const int PAGE_SIZE = 5;
        public Paginator Pager { get; set; }
        [BindProperty(SupportsGet = true)]
        public int? currentpage { get; set; }   
        #endregion

        [BindProperty(SupportsGet = true)]
        public string searchBy { get; set; }

        [BindProperty(SupportsGet = true)]
        public string searchArg { get; set; }

        [BindProperty(SupportsGet = true)]
        public string playlistname { get; set; }

        public List<TrackSelection> trackInfo { get; set; }

        public List<PlaylistTrackInfo> qplaylistInfo { get; set; }

        //this property will be tied to the INPUT fields of the web page
        //this list is tied to the table data elements for the playlist
        [BindProperty]
        public List<PlaylistTrackTRX> cplaylistInfo { get; set; }

        //this property is tied to the form input element located on each
        //  of the rows of the track table
        //it will hold the trackid one wish to attempt to add to the playlist
        [BindProperty]
        public int addtrackid { get; set; }

        public const string USERNAME = "HansenB";
        public void OnGet()
        {
            //this method is executed everytime the page is call for the first time
            //   OR
            //whenever a Get request is made to the page SUCH AS RedirectToPage()
            GetTrackInfo();
            GetPlaylist();
        }

        public void GetTrackInfo()
        {
            if (!string.IsNullOrWhiteSpace(searchArg) &&
                            !string.IsNullOrWhiteSpace(searchBy))
            {
                int totalcount = 0;
                int pagenumber = currentpage.HasValue ? currentpage.Value : 1;
                PageState current = new(pagenumber, PAGE_SIZE);
                trackInfo = _trackServices.Track_FetchTracksBy(searchArg.Trim(),
                    searchBy.Trim(), pagenumber, PAGE_SIZE, out totalcount);
                Pager = new(totalcount, current);
            }
        }

        public void GetPlaylist()
        {
            if (!string.IsNullOrWhiteSpace(playlistname))
            {
                string username = USERNAME;
                qplaylistInfo = _playlisttrackServices.PlaylistTrack_FetchPlaylist(playlistname.Trim(), username);
            }
        }
        public IActionResult OnPostTrackSearch()
        {
            try
            {
                if (string.IsNullOrWhiteSpace(searchBy))
                {
                    Errors.Add(new Exception("Track search type not selected"));
                }
                if (string.IsNullOrWhiteSpace(searchArg))
                {
                    Errors.Add(new Exception("Track search string not entered"));
                }
                if (Errors.Any())
                {
                    throw new AggregateException(Errors);
                }
                //RedirectToPage() will cause an Get request to be issue (OnGet())
                return RedirectToPage(new
                {
                    searchBy = searchBy.Trim(),
                    searchArg = searchArg.Trim(),
                    playlistname = string.IsNullOrWhiteSpace(playlistname) ? " " : playlistname.Trim()
                });
            }
            catch (AggregateException ex)
            {
                ErrorMessage = "Unable to process search";
                foreach (var error in ex.InnerExceptions)
                {
                    ErrorDetails.Add(error.Message);
                    
                }
                return Page();
            }
            catch (Exception ex)
            {
                ErrorMessage = GetInnerException(ex).Message;
                return Page();
            }
        }

        public IActionResult OnPostFetch()
        {
            try
            {
                if (string.IsNullOrWhiteSpace(playlistname))
                {
                    throw new Exception("Enter a playlist name to fetch.");
                }
                return RedirectToPage(new
                {
                    searchBy = string.IsNullOrWhiteSpace(searchBy) ? " " : searchBy.Trim(),
                    searchArg = string.IsNullOrWhiteSpace(searchArg) ? " " : searchArg.Trim(),
                    playlistname = playlistname.Trim()
                });
            }
            catch(Exception ex)
            {
                ErrorMessage = GetInnerException(ex).Message;
                return Page();

            }
        }

        public IActionResult OnPostAddTrack()
        {
            try
            {
                if (string.IsNullOrWhiteSpace(playlistname))
                {
                    throw new Exception("You need to have a playlist select first. Enter a playlist name and Fetch");
                }

                // Add the code to add a track via the service.
                // the data needed for your call has ALREADY been placed in your local
                //      property by the use of [BindProperty] which is two way (output/input)
                // once security is install, you would be able to obtain the user name
                //      from the operating system
                string username = USERNAME;
                //call your service sending in the expected data
                _playlisttrackServices.PlaylistTrack_AddTrack(playlistname, username, addtrackid);
                FeedBackMessage = "adding the track";
                return RedirectToPage(new
                {
                    searchby = searchBy,
                    searcharg = searchArg,
                    playlistname = playlistname
                });
            }
            catch (AggregateException ex)
            {
                              
                ErrorMessage = "Unable to process add track";
                foreach (var error in ex.InnerExceptions)
                {
                    ErrorDetails.Add(error.Message);

                }
                //Since the OnGet() will NOT be called if there is a transaction
                //      error, the catch MUST do the actions of the OnGet
                GetTrackInfo();
                GetPlaylist();

                return Page();
            }
            catch (Exception ex)
            {
                ErrorMessage = GetInnerException(ex).Message;
                GetTrackInfo();
                GetPlaylist();

                return Page();
            }
            
        }

        public IActionResult OnPostRemove()
        {
            try
            {
               //Add the code to process the list of tracks via the service.

                return RedirectToPage(new
                {
                    searchBy = string.IsNullOrWhiteSpace(searchBy) ? " " : searchBy.Trim(),
                    searchArg = string.IsNullOrWhiteSpace(searchArg) ? " " : searchArg.Trim(),
                    playlistname = playlistname
                });
            }
            catch (AggregateException ex)
            {

                ErrorMessage = "Unable to process remove tracks";
                foreach (var error in ex.InnerExceptions)
                {
                    ErrorDetails.Add(error.Message);

                }
                GetTrackInfo();
                GetPlaylist();

                return Page();
            }
            catch (Exception ex)
            {a
                ErrorMessage = GetInnerException(ex).Message;
                GetTrackInfo();
                GetPlaylist();

                return Page();
            }

        }



        public IActionResult OnPostReOrg()
        {
            try
            {
                //Add the code to process the list of tracks via the service.

                return RedirectToPage(new
                {
                    searchBy = string.IsNullOrWhiteSpace(searchBy) ? " " : searchBy.Trim(),
                    searchArg = string.IsNullOrWhiteSpace(searchArg) ? " " : searchArg.Trim(),
                    playlistname = playlistname
                });
            }
            catch (AggregateException ex)
            {

                ErrorMessage = "Unable to process remove tracks";
                foreach (var error in ex.InnerExceptions)
                {
                    ErrorDetails.Add(error.Message);

                }
                GetTrackInfo();
                GetPlaylist();

src/ChinookSolution/WebApp/Pages/SamplePages/Basics.cshtml
@page
@model WebApp.Pages.SamplePages.BasicsModel
@{
    //  The cshtml page contains both cs code and html code
    //  The @ symbol takes processing from the html environment
    //      and moves it to the C# environment
    //  Processing any html code moves processing into the html
    //      environment

    //  Set the text for the browser window tab
    ViewData["Title"] = "Review page basics";
}
<h1>Basics of Razor Page (Review)</h1>

<h3>Demonstration of OnGet request processing</h3>
@if (string.IsNullOrWhiteSpace(Model.MyName))
{
    <p>The random number is odd</p>
}
else
{
    <p>@Model.MyName</p>
}

<h3>Demostration of OnPost request processing for a form</h3>
<form method="post">
    <label>
        Enter a number
        <input type="number" asp-for="ID" /><br />
    </label>
    <button type="submit" value="A" id="theButtonA" name="theButton">A Button</button>
    &nbsp;&nbsp;
    <button type="submit" value="B" id="theButtonB" name="theButton">B Button</button>
</form>
<br/>
<p style="color: forestgreen; font-weight: bold;">@Model.FeedBack</p>

src/ChinookSolution/WebApp/Pages/SamplePages/Controls.cshtml
@page
@model WebApp.Pages.SamplePages.ControlsModel
@{
    ViewData["Title"] = "Various FOr Controls";
}
@section CustomCSS
    {
    @*
        The file _MyCustomCSS contains valid code that represents css.
        THe partial tag will bring in the contents of the file.
        The section reference of CustomCSS will be place the file contents
            on the layout page in the "named" RenderSection
    *@
    <partial name="_MyCustomCSS" />
}

    <h1>Various Form Controls</h1>
@if (!string.IsNullOrWhiteSpace(Model.Feedback))
{
    <p>@Model.Feedback</p>
}
<section class="setflex">
    <div class=onethird>
        <h3>TextBoxes</h3>
        <form method="post">
            <label>
                Enter an Email
                <input type="email" asp-for="EmailText"
                       placeholder="enter email" />
            </label>
            <br />
            <label>
                Enter an password
                <input type="password" asp-for="PasswordText"
                       placeholder="enter password" />
            </label>
            <br />
            <label>
                Enter an Date
                <input type="date" asp-for="DateText" />
            </label>
            <br />
            <label>
                Enter an Time
                <input type="time" asp-for="TimeText" />
            </label>
            <br />

            <button type="submit" value="textbox" id="theTextButton"
                    name="theTextButton" asp-page-handler="TextBox">
                Text Submit
            </button>
        </form>
    </div>
    <div class=onethird>
        <h3>Radiobuttons CheckBox TextArea</h3>
        <form method="post">
            <label>
                Select favourite meal<br />
            </label>
            @*<input type="radio" value="breakfast" asp-for="Meal"/>
            &nbsp;Breakfast<br/>
            <input type="radio" value="lunch" asp-for="Meal"/>
            &nbsp;Lunch<br/>
            <input type="radio" value="Supper" asp-for="Meal"/>
            &nbsp;Supper<br/>
            <input type="radio" value="Snacks" asp-for="Meal"/>
            &nbsp;Snacks<br/>
            *@
            @foreach (var item in Model.Meals)
            {
                @*  Need a space before the display item *@
                <input type="radio" value="@item" asp-for="Meal" /> @item

                <br />
            }
            <label>
                <input type="checkbox" value="true" asp-for="AcceptanceBox" />
                &nbsp; I agree to terms
            </label>
            <br />
            <label>
                Message
                <textarea rows="5" cols="50" placeholder="enter message"
                          asp-for="MessageBody"></textarea>
            </label>
            <button type="submit" value="radiocheckarea" id="theRadioCheckAreaButton"
                    name="theRadioCheckAreaButton" asp-page-handler="RadioCheckArea">
                Radio/Check/Area Submit
            </button>
        </form>
    </div>
    <div class=onethird>
        <h3>List and Slider</h3>
        <form method="post">
            <label>
                Slect your favourite Ride
                <select asp-for="MyRide">
                    <option value="0">Select ride ...</option>
                    @foreach (var ride in Model.Rides)
                    {
                        <option value="@ride.ValueID">@ride.DisplayText</option>
                    }
                </select>
            </label>
            <br/>
            <label>
                Select your favorite Vacation Spot
                <input type="text" asp-for="VacationSpot"
                       list="VacationChoices" />
                <datalist id="VacationChoices">
                    @foreach (var spot in Model.VacationSpots)
                    {
                        <option value="@spot"></option>
                        //  <option value="@spot">@spot</option>
                    }
                </datalist>
            </label>
            <br/>
            <label>
                Rate the form control reivew (bad < - > good)
                <input type="range" min="0" max="10" step="1" value="5"
                       asp-for="ReviewRating"/>
            </label>
            <button type="submit" value="listslider" id="theListSliderButton"
                    name="theListSliderButton" asp-page-handler="ListSlider">
                Slider Submit
            </button>
        </form>
    </div>
</section>

src/ChinookSolution/WebApp/Pages/SamplePages/PlaylistManagement.cshtml
@page "{searchBy?}/{searchArg?}/{playlistname?}"
@model WebApp.Pages.SamplePages.PlaylistManagementModel
@{
    ViewData["Title"] = "Playlist Management";
}

@section CustomCSS{
    <partial name=_MyCustomCSS />
}
<h1>Playlist Management</h1>
<blockquote>
    This page has  been created to demonstrate an UI interface for bulk maintenance
    of data on the database, commonly referred to as <b>transactional processing</b>.
    The page will allow the user to create or alter a list of tracks (Add, reorgnaize,
    and remove) of a playlist.
    <br/><br/>
    Several UI techniques will be employeed on this page. This is not the only way
    the interface could have been done. Special note should be directed to the 
    display and collection of data from the Playlist table. This table will demonstrate
    an implementation of using CQRS data models. The error list display demonstrates the
    display of having multiple errors returned from a business service.

</blockquote>

@if (Model.HasFeedBack)
{
    <blockquote class="success">@Model.FeedBackMessage</blockquote>
}

@if (Model.HasError)
{
    <blockquote class="error">
        @Model.ErrorMessage
        <ul>
            @foreach (var detail in Model.ErrorDetails)
            {
                <li>@detail</li>
            }
        </ul>
    </blockquote>
}
<section class="setflex">
    <div class="onehalf">
        <form method="post">
        <label>
            Search pattern
            <input type="text" asp-for="searchArg" />
            <br/>
            <input type="radio" asp-for="searchBy" value="Artist"/>&nbsp;&nbsp;Artist
            &nbsp;&nbsp;
            <input type="radio" asp-for="searchBy" value="Album"/>&nbsp;&nbsp;Album
            &nbsp; &nbsp;
            <button type="submit" asp-page-handler="TrackSearch"
               title="Fetch tracks">Tracks ?</button>
        </label>
        </form>
        @if(!string.IsNullOrWhiteSpace(Model.searchArg)
             && !string.IsNullOrWhiteSpace(Model.searchBy))
        {
          if(Model.trackInfo.Count() == 0)
            {
                <p style="color:blue;font-weight:bold; font-size:large">
                    No tracks matching search request.
                </p>
            }
            else
            {
                <table>
                    <thead>
                        <tr>
                            <th></th>
                            <th>Song</th>
                            <th>Album</th>
                            <th>Artist</th>
                            <th>Length</th>
                            <th>Price</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.trackInfo)
                        {
                            <tr>
                                <td>
                                    @* code to demo a button on a table 
                                        using a icon
                                    *@
                                    <form method="post">
                                        <input type="hidden" value="@item.TrackId"
                                            asp-for="addtrackid">
                                        <button type="submit" title="Add this Track"
                                            asp-page-handler="AddTrack">
                                         <i class="las la-plus"></i>
                                        </button>
                                    </form>
                                </td>
                                <td>@item.SongName</td>
                                <td>@item.AlbumTitle</td>
                                <td>@item.ArtistName</td>
                                <td>@TimeSpan.FromMilliseconds(item.Milliseconds).ToString(@"mm\:ss")</td>
                                <td>@item.Price</td>
                            </tr>
                        }
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="6">
                                @{
                                    foreach (var pageRef in Model.Pager)
                                    {
                                        // I can use the == because of PageRef type being a C# 9 record type
                                        if (pageRef == Model.Pager.CurrentPage)
                                        {
                                            <b>@pageRef.Text</b>
                                        }
                                        else
                                        {
                                            <a title="Page @pageRef.Page" asp-page="/SamplePages/PlaylistManagement"
                                            asp-route-currentpage="@pageRef.Page">@pageRef.Text</a>
                                        }
                                    }
                                }
                            </td>
                        </tr>
                    </tfoot>
                </table>
            }
        }
    </div>
    <div class="onehalf">
       <form method="post" id="playlist">

            <label>
                Enter playlist name:
                <input type="text" asp-for="playlistname" />
            </label>
            <br />
            <button tye="submit" title="Retreive Playlist"
                    asp-page-handler="Fetch">
                Fetch List
            </button>&nbsp;&nbsp;
            @if(Model.qplaylistInfo != null &&
                Model.qplaylistInfo.Count > 0)
                {
                    <button tye="submit" title="Remove tracks"
                            asp-page-handler="Remove"
                            style="background-color:var(--danger-color)">
                        Remove Tracks
                    </button>
                }
                &nbsp;&nbsp;
             @if(Model.qplaylistInfo != null &&
                Model.qplaylistInfo.Count > 0)
                {
                    <button tye="submit" title="Reorganize playlist"
                            asp-page-handler="ReOrg">
                        Re-Org Tracks
                    </button>
                }
            <br /><br />
            @if (Model.qplaylistInfo != null)
            {
                if (Model.qplaylistInfo.Count == 0)
                {
                    <p style="color:blue; font-weight:bold;">This playlist is empty or does not exist. Adding a track will create the playlist.</p>

                }
                else
                {
                    <table>
                        <thead>
                            <tr>
                                <th></th>
                                <th>Trk #</th>
                                <th>Song</th>
                                <th>length</th>
                                <th>Reorg Trk#</th>
                            </tr>
                        </thead>

                        <tbody>
                           @* code to demo CQRS for a table display

                           a) createe an incoming control (hidden) that will act as an
                                "unique index identifier" for each instance that will be created.

                                <input type="hidden" name="commandmodelpropertyname.Index"
                                        value="@intanceitem.uniqueidentityproperty">

                                <input type="hidden" name="cplaylistinfo.Index"
                                value="@item.TrackId">

                            b)for the display of the table 
                                on each property of the row instance, use the value of your unique index
                                    indentifier as an "[index]" attach to the name of the field

                                <input type="text"
                                        name-"cplaylistinfo[@item.TrackId].propertyname"
                                        value="@trackinput">
                                
                              ALL incoming data that belons to the smae"[ind]" will be collected 
                              into the SAME instance row and placed into your command model List<T>

                              NOTE: using this technique of name/value pair REEPLACES the asp-for parameter
                           *@
                           @foreach(var item in Model.qplaylistInfo)
                           {
                               <tr>
                                   <td>
                                        <input type="hidden" name="cplaylistinfo.Index"
                                                        value="@item.TrackId">
                                        <input type="hidden"
                                            name="cplaylistinfo[@item.TrackId].TrackId"
                                            value="@item.TrackId">
                                        <input type="checkbox" 
                                             name="cplaylistinfo[@item.TrackId].SelectedTrack"
                                             value="true">
                                   </td>
                                   <td>
                                        <input type="hidden"
                                               name="cplaylistinfo[@item.TrackId].TrackNumber"
                                               value="@item.TrackNumber">
                                        @item.TrackNumber
                                   </td>
                                   <td>
                                       @item.SongName
                                   </td>
                                   <td>
                                       @TimeSpan.FromMilliseconds(item.Milliseconds).ToString(@"mm\:ss")
                                   </td>
                                   <input type="text"
                                        name="cplaylistinfo[@item.TrackId].TrackInput">
                                        
                               </tr>
                           }
                        </tbody>
                    </table>
                }

            }
        </form>
    </div>
</section>