ListToList/WebApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace WebApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ListToList/WebApp/Pages/Index.cshtml.cs
#nullable disable
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NorthWind.BLL;

namespace WebApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly ProductServices _productServices;

        //  command model (Will be updating the table/entity with these records/items)  //  Sales Lines
        [BindProperty] public List<NorthWind.ViewModel.ProductViewModel> NewSaleItems { get; set; } = new();

        //  query model (This is the initial data that we received from our entities)  //  Inventory
        [BindProperty] public List<NorthWind.ViewModel.ProductViewModel> Items { get; set; }

        //  product id that is used to select from my items and transfer to my sales itesm
        [BindProperty] public int SelectedProductID { get; set; }

        //  product id that is used to select the command model on my sale items and update he totals (qty * price)
        [BindProperty] public int RefreshProductID { get; set; }

        //  product id that is used to remove the command model from my sales item and then used to update my item query model
        [BindProperty] public int RemoveProductID { get; set; }




        public IndexModel(ILogger<IndexModel> logger, ProductServices productServices)
        {
            _logger = logger;
            _productServices = productServices;
        }

        public void OnGet()
        {
            //  Update my items query model
            Items = _productServices.GetProducts();
        }

        //  Add command model items to sales list
        public IActionResult OnPostAddItem()
        {
            // selectedItem holds the value of the pressed button
            var selectedItem = Items.SingleOrDefault(x => x.ProductID == SelectedProductID);
            if (selectedItem != null)
            {
                //  remove the item (query model) from the inventory list
                Items.Remove(selectedItem);
                //  update the item/command model with initial values
                selectedItem.Quantity = 1;
                selectedItem.Total = selectedItem.UnitPrice * selectedItem.Quantity;
                //  add item (command model) to  sale item list
                NewSaleItems.Add(selectedItem);
            }
            //  OnGet does NOT Fire
            return Page();
        }

        //  remove command model item from sale item list and refresh the query modem inventory list with a clean record
        public IActionResult OnPostRemoveItem()
        {
            //  get my query model
            var selectedItem = NewSaleItems.SingleOrDefault(x => x.ProductID == RemoveProductID);
            if (selectedItem != null)
            {
                //  remove the item (query model) from the items list
                NewSaleItems.Remove(selectedItem);
                Items.Add(_productServices.GetProductByProductID(RemoveProductID));
                Items = Items.OrderBy(x => x.ProductName).ToList();
            }
            //  OnGet does NOT Fire
            return Page();
        }

        //  Refresh line total
        public IActionResult OnPostRefreshItem()
        {
            var selectedItem = NewSaleItems.SingleOrDefault(x => x.ProductID == RefreshProductID);
            if (selectedItem != null)
            {
                selectedItem.Total = selectedItem.UnitPrice * selectedItem.Quantity;
            }
            //  OnGet does NOT Fire
            return Page();
        }
    }
}

ListToList/WebApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ListToList/WebApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<h2>Sale Lines</h2>
<form method="post">
    <table width="100%">
        <col style="width:10%">
        <col style="width:10%">
        <col style="width:30%">
        <col style="width:10%">
        <col style="width:10%">
        <col style="width:10%">
        <col style="width:10%">
        <thead>
            <tr>
                <th> </th>
                <th>ProductID</th>
                <th>ProductName</th>
                <th>UnitPrice</th>
                <th>Quantity</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var saleItem in Model.NewSaleItems)
            {
                <tr>
                    <td>
                        <input type="hidden" name="NewSaleItems.Index" value="@saleItem.ProductID" />
                        @* name and value are used instead of asp-for
                    these are used here because we are going to a list of item
                    and we need to index the individual instances in some fashion*@
                        <button type="submit" name="RemoveProductID" value="@saleItem.ProductID"
                            asp-page-handler="RemoveItem">
                            Remove
                        </button>
                    </td>
                    <td>
                        @* tie value to incoming data index (see button above)
                    The item.Name is the field of interest*@
                        <input type="hidden" name="NewSaleItems[@saleItem.ProductID].ProductID" value="@saleItem.ProductID" readonly />
                        <span style="display:inline-block; width: 16px; height: 16px; background-color:@saleItem.ProductID"></span>
                        @saleItem.ProductID
                    </td>
                    <td>
                        @* tie value to incoming data index (see button above) *@
                        <input type="hidden" name="NewSaleItems[@saleItem.ProductID].ProductName" value="@saleItem.ProductName" readonly />
                        @saleItem.ProductName
                    </td>
                    <td>
                        @* tie value to incoming data index (see button above) *@
                        <input type="number" name="NewSaleItems[@saleItem.ProductID].UnitPrice" value="@saleItem.UnitPrice" min="0.00" step="0.01"/>
                    </td>
                    <td>
                        <input type="number" name="NewSaleItems[@saleItem.ProductID].Quantity" value="@saleItem.Quantity" min="0" step="0"/>
                    </td>
                    <td>
                        @* tie value to incoming data index (see button above) *@
                        <input type="hidden" name="NewSaleItems[@saleItem.ProductID].Total" value="@saleItem.Total" readonly />
                        @saleItem.Total
                    </td>
                    <td>
                        <input type="hidden" name="NewSaleItems.Refresh" value="@saleItem.ProductID" />
                        @* name and value are used instead of asp-for
                    these are used here because we are going to a list of item
                    and we need to index the individual instances in some fashion*@
                        <button type="submit" name="RefreshProductID" value="@saleItem.ProductID"
                            asp-page-handler="RefreshItem">
                            Recalc Line
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <br />
    <br />
    <h2>Inventory</h2>
    <table>
        <thead>
            <tr>
                <th> </th>
                <th>ProductID</th>
                <th>ProductName</th>
                <th>UnitPrice</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Items)
            {
                <tr>
                    <td>
                        <input type="hidden" name="Items.Index" value="@item.ProductID" />
                        @* name and value are used instead of asp-for
                    these are used here because we are going to a list of item
                    and we need to index the individual instances in some fashion*@
                        <button type="submit" name="SelectedProductID" value="@item.ProductID"
                            asp-page-handler="AddItem">
                            Add
                        </button>
                    </td>
                    <td>
                        @* tie value to incoming data index (see button above)
                    The item.Name is the field of interest*@
                        <input type="hidden" name="Items[@item.ProductID].ProductID" value="@item.ProductID" readonly />
                        <span style="display:inline-block; width: 16px; height: 16px; background-color:@item.ProductID"></span>
                        @item.ProductID
                    </td>
                    <td>
                        @* tie value to incoming data index (see button above) *@
                        <input type="hidden" name="Items[@item.ProductID].ProductName" value="@item.ProductName" readonly />
                        @item.ProductName
                    </td>
                    <td>
                        @* tie value to incoming data index (see button above) *@
                        <input type="hidden" name="Items[@item.ProductID].UnitPrice" value="@item.UnitPrice" readonly />
                        @item.UnitPrice
                    </td>
                </tr>
            }
        </tbody>
    </table>
</form>

ListToList/WebApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">WebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>