SimpleNonIndexList/SimpleNonIndexList/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace SimpleNonIndexList.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

SimpleNonIndexList/SimpleNonIndexList/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SimpleNonIndexList.ViewModel;

namespace SimpleNonIndexList.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        [BindProperty] public List<Employee> Employees { get; set; } = new List<Employee>();

        [BindProperty] public int RemoveEmployeeID { get; set; }

        [BindProperty] public string EmployeeName { get; set; }

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
            //Employees.Add(new Employee() { EmployeeId = 1, Name = "James" });
        }

        public void OnGet()
        {
     
        }

        public void OnPostRemoveEmployee()
        {
            var selectedItem = Employees.FirstOrDefault(x => x.EmployeeId == RemoveEmployeeID);
            if (selectedItem != null)
            {
                Employees.Remove(selectedItem);
            }
        }

        public void OnPostAddToEmployeeList()
        {
            int maxID = Employees.Count == 0
               ? 1
               : Employees.OrderBy(x => x.EmployeeId)
                   .Max(x => x.EmployeeId) + 1;
            Employees.Add(new Employee() { EmployeeId = maxID, Name = EmployeeName });

        }
    }
}

SimpleNonIndexList/SimpleNonIndexList/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SimpleNonIndexList.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

SimpleNonIndexList/SimpleNonIndexList/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<main style="display:flex">
    <form method="post">
        <div style="display:flex;">
            <section class="lefthalfpage">
                <label>
                    Name
                    <input type="text" asp-for="EmployeeName" />
                </label>
                <button type="submit" asp-page-handler="AddToEmployeeList">Add to employee list</button>
                
            </section>
        <section class="righthalfpage">
            <table>
                <thead>
                @*used for column titles*@
                <tr>
                    <th> </th>
                    <th>Names</th>
                </tr>
                </thead>
                <tbody>
                @foreach (var employee in Model.Employees)
                {
                    <tr>
                        <td>
                            <input type="hidden" name="Employees.Index" value="@employee.EmployeeId"/>
                            <button type="submit" name="RemoveEmployeeID" value="@employee.EmployeeId"
                                    asp-page-handler="RemoveEmployee">
                                Remove
                            </button>
                                    @employee.EmployeeId
                        </td>
                        <td>
                            <input type="hidden" name="Employees[@employee.EmployeeId].EmployeeID" value="@employee.EmployeeId" readonly/>
                        </td>
                        <td>
                            <input type="hidden" name="Employees[@employee.EmployeeId].Name" value="@employee.Name" readonly/>
                            @employee.Name
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </section>
        </div>
    </form>
</main>

SimpleNonIndexList/SimpleNonIndexList/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/holiday.css@0.9.8" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FSISWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">SimpleNonIndexList</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SimpleNonIndexList - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>